### ISSUE TITLE
【查詢資訊權限】 後端 總整理

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#158]
【查詢資訊權限】 後端 總整理
===

### 介紹
檢查使用者是否已經留過一筆資料，或推薦一位使用者留下一筆資訊。
若有，則有查詢所有資訊的權限，若沒有，則僅能查詢最新薪時資訊的前10筆，以職稱、公司搜尋的功能都不能使用。

整個查詢資訊權限後端的部分，分為幾個子任務:

### 子任務
- [x] <strong> 取得使用者推薦者字串 </strong>: 讓該使用者(稱為A)取得唯一的一個字串，藉此產生連結，當其他使用者(稱為B)上傳資訊時，可以用這個字串在後端反查到使用者A的資訊，藉以知道B上傳的資訊是由A推薦的。  issue: #143  PR: #145 

- [x] <strong>上傳推薦者資訊</strong>: 上傳薪時資訊時，將推薦者字串一併上傳，並查詢MongoDB，找到推薦者的資訊。再將推薦者資訊連同新時資訊一併上傳到MongoDB。 Issue: #143 PR: #153 

- [x] <strong>權限檢驗</strong>: 使用者送FB給定的access_token，確認該名使用者的身分、並確認其是否有查詢資訊的權限。詳細驗證方式，請看 [後端流程說明圖](https://docs.google.com/drawings/d/1myw2fKOH4MRJpvptGyJGvFRuNGm3xMgk6sKa9OgDW28/edit?usp=sharing)，分為Authentication(身分認證) & Authorization(查詢權限認證)兩個部分。Issue: #134  PR: #137, #140, #147, #163

- [x] <strong>與查詢資訊的API整合</strong>: 當使用有權限，則可以查詢任何資訊。當使用者沒有權限，僅能查詢最新薪時資訊的前10筆。 Issue: #149  PR: #160 [hackmd link](https://hackmd.io/s/HyAkcrWHx)

- [x] <strong>使用者查詢資訊權限API</strong>: 獨立的一個API，讓使用者可以確認使否有查詢資訊的權限。 Issue: #157   [hackmd link](https://hackmd.io/s/HJ28Exzrx)
