### ISSUE TITLE
將 User 相關的程式 Refactoring

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#281]
**原因**

1. 各 API, function 中，user 與 user_id 詞混用，例如

`libs/search-permission.js`
```
function getDataNumOfUser(db, user) {
  return db.collection('authors').find({_id: user}).toArray().then(results => {
```

指的是傳入 user `{id, type}` 的形式， 尋找 `find({_id: user})` ，又變成 _id （user_id, user 要統一用語）

2. `req.user` 實際上拿到的也不是真 User，而是 `user_id: {id, type}` （req.user 要統一）

3. 考慮未來如果引入 passport，勢必要有一個統一的 User Model，減少混亂 （要有 User Model）

4. 對 BSON 而言， {id, type} !== {type, id}，所以必須確保順序的一致性 （user_id 用單純的 ObjectId 比較好）

---

**可能地執行步驟：**

1. 建立 User Model, users collection

這部分包含將現有的資料轉移，與 DB 有關的地方做對應轉換

```
 /*
   @param user {id, type}
 */
 function getDataNumOfUser(db, user) {
-    return db.collection('authors').find({_id: user})
+    return db.collection('users').find({'facebook_id': user.id})
```

2. Authentication, AuthenticationMiddleware 開始提供 user 與 req.user 是真 User

3. 與 User 相關的 function 轉換成只透過 user_id 做查詢

---

**影響範圍**

dev/3.x, dev/4.x 都會被影響，不過 dev/4.x 影響幅度小

---

**TODOs** (新更新)

- [x] 建立 users，將 author 轉移至 users (#282, #295)
- [x] Authentication Library 要 resolve 出驗證的 User (#286, #295)
- [x] req.user 轉移成 User (#286, #295)
- [x] 其它部分的 code 轉移成用 user_id 參數 (#323 解決一部分)

**Comment by h091237557** [comment]
同意要改 ~ 不過有兩個問題要問一下。
1. `req.user 實際上拿到的也不是真 User` 這段話的真user大概是長啥樣?
2. 上面說到的passport是啥???

**Comment by mark86092** [comment]
@h091237557 

1. 目前拿到的 req.user 長這樣：{id: 'xxx', type: 'facebook'}，我覺得如果要完整一點，

就是要 users collection 當中的一個 doc 當作 req.user

eg: `{_id: {id: 'xxx', type: 'facebook'}, queries_count: 1}` 這樣

當然，Users 的 Model 沒有完全確認，但至少可以確定，目前的 req.user 拿到的是 _id

2. passport 是 http://passportjs.org/，用來幫忙做 Token，OAuth 登入等

**Comment by barry800414** [comment]
目前的想法是
`user`: 是個物件，裡面有若干key & value (我們可以定義清楚），不見得要是collection的整個doc。
`user_id`: 我 prefer 用 `users` 這個 collection的 `_id` 欄位。因為如果未來要綁定多帳號，一個使用者可能就會有 `{ id:xxx, type:'facebook' }` `{ id:ooo, type:'google'}` 兩組ＩＤ。這樣在檢查使用者是否為同一人會有困擾。

**Comment by mark86092** [comment]
> `user`: 是個物件，裡面有若干key & value ，我們可以定義清楚，不見得要是collection的整個doc。

補充：就是 User Model 是從 users collection 查詢來的

> user_id: 我 prefer 用 users 這個 collection的 _id 欄位。

是的，想要讓名字統一在這，是 users 的 _id 就用 user_id 這詞

#276 提出來的一個 User Model，的確是想解決 @barry800414 提到的問題

```
{
  _id: xxx
  [facebook_id]: xxx
  [name]: 例如有存名字？
  [google_id]
}
```

**Comment by mark86092** [comment]
更新 TODO

**Comment by barry800414** [comment]
確定一下 `users` 這個collections的欄位喔

目前確定有的：
```
{
     _id: xxxx(mongodb id),
     facebook_id: xxxx (facebook id), 
     time_and_salary_count: xxx,
     recommendation_string: xxx, 
}
```

對嗎？  我要更新到DB doc  上

**Comment by mark86092** [comment]
不是，我晚點再更新上去

**Comment by barry800414** [comment]
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/286

然後這個看不太懂，為什麼要用 `facebook` 欄位

**Comment by mark86092** [comment]
@barry800414 在我們的 case Model 就是 collection 取出來的 record，所以這邊就不強調 Model 是啥（如果要改定義，麻煩另開地方）

facebook 是存放跟 facebook 有關的資訊，原則上，facebook.id == facebook_id，不過我這邊不想要這麼多層，所以特別取出 facebook_id, google_id 等

BTW, PR 開一個禮拜可以看，slack 也有放，可以早點反應

**Comment by barry800414** [comment]
沒來得及看是我的問題啦。很多東西都改太大，我必須說，我沒有辦法在下班後還能集中精神看。
我是覺得這種做法有點令人confused，何必多此一舉。

另外哪邊有寫到 user model 就是 users collection 取出來的 doc ?
我其實是想要有個文件可以看，讓我知道現在結論到底是什麼

一堆討論串，很多人有提出意見，都寫例如例如，我不知道哪一個才是確定版，然後又已經送幾個ＰＲ了。
或者是晚上討論吧，我看了很久還是不能理解現況

**Comment by barry800414** [comment]
疑問列表，麻煩 @mark86092 回覆了
1. `users` collection 最後會有什麼欄位？
2. User Model 是什麼？
3. 真User是什麼？
4. TODO裡面：
>  Authentication Library 要 resolve 出驗證的 User 
> req.user 轉移成 User

這邊的User 指的是什麼？

**Comment by mark86092** [comment]
分幾個項目說明：

1. users collection

```
_id: ObjectId
[facebook_id]: Facebook unique id, partial unique index
[facebook]: 這邊放 Facebook 帳號相關的資訊，可能有 name, id, email 等欄位
```
目前 facebook 欄位沒有任何欄位，需要透過 workings collection 來補充

這也是我先抽出 facebook_id 這個欄位的原因

2. 一筆 users collection 的紀錄稱作 user，是一個物件 object， 例如：

user --> {_id: new ObjectId(), facebook_id: '123456789'}

3. 代表 users collection 的欄位特徵是 User Model，與 collection 有同樣的欄位，用來稱呼 user 集合

**Comment by mark86092** [comment]
Authentication Library

1) 原本 resolve 出 `{id, type}` 這個物件，既沒定義是什麼，也找不到 DB 的對應
2) 後來 resolve 出合法的 user

req.user
1) 原本是 `{id, type}` 這個物件
2) 後來必須是 User instance 或是 null
