### ISSUE TITLE
migrate user related fields 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#560]
拿到 production 才知道我們使用者相關的欄位有點複雜：

1. `workings` collection：裡面存 `author` object，裡面有 id ，但不是 users collection 裡面的 _id ，而是 `facebook_id`

2. `experience_likes`, `popular_experience_logs`, `reply_likes`, `reports` collection ：裡面存 `user_id`，就是 `users` collection 的 `_id`

3. `experiences`, `replies` collection ：裡面存 `author_id` ，就是 `users` collection 的 `_id`

想要全部統一成 `user_id` 欄位，是個浩大工程 orz 

## TODO
- [ ] migration: `workings` collection
- [ ] migration: `experiences` collection
- [ ] migration: `replies` collection
- [ ] workings 相對應所有的 API 修改
- [ ] experiences 相對應所有的 API 修改
- [ ] replies 相對應所有的 API 修改

**Comment by mark86092** [comment]
author_id 我覺得還好，有印象當初討論 api，寫 author_id 的人是說作者，所以就不採用 user_id，才會是這樣

當然換成 user_id 我個人覺得ＯＫ

**Comment by LittleWhiteYA** [comment]
這個我寫 script 的時候又遇到這問題...
