### ISSUE TITLE
後端 POST 經驗 的 GraphQL Migration TODO

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#659]
- [ ] Graphql 端的 Input 檢查，例如：檢查 0 <= salary < 2^32
- [ ] Graphql 端的 Test 撰寫
- [ ] job_title 轉大寫，company_query 目前都是與舊 API 行為有變，要檢查
