### ISSUE TITLE
refactor: remove deprecated api

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#871]
移除以下幾隻 restful API 且保留相關測試

- [x] `POST /auth/facebook` & `POST /auth/google` (done in #780)
- [x] `GET /jobs/search` (done in #870)
- [x] `POST & DELETE /replies/:id/like` (done in #781)
- [ ] `POST /interview_experiences` (https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/713)
- [ ] `POST /work-experiences` (https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/713)
- [ ] `POST /experiences/:id/likes`
- [ ] `DELETE /experiences/:id/likes`
